const MS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;

const ONE_SECOND_MILLI_SECONDS = 1 * MS_PER_SECOND;
const ONE_MINUTE_MILLI_SECONDS = ONE_SECOND_MILLI_SECONDS * SECONDS_PER_MINUTE;
const ONE_HOUR_MILLI_SECONDS = ONE_MINUTE_MILLI_SECONDS * MINUTES_PER_HOUR;
const ONE_DAY_MILLI_SECONDS = ONE_HOUR_MILLI_SECONDS * HOURS_PER_DAY;

export {
    MS_PER_SECOND,
    SECONDS_PER_MINUTE,
    MINUTES_PER_HOUR,
    HOURS_PER_DAY,

    ONE_SECOND_MILLI_SECONDS,
    ONE_MINUTE_MILLI_SECONDS,
    ONE_HOUR_MILLI_SECONDS,
    ONE_DAY_MILLI_SECONDS
};
